/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rouletteApp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.redis.repository.configuration.EnableRedisRepositories;

@SpringBootApplication
@EnableRedisRepositories
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class,args);
    }
}
